version: "3.8"

services:

  sftp:
    image: atmoz/sftp:alpine
    volumes:
        - ./upload:/home/foo/upload
    ports:
        - "2222:22"
    command: foo:pass:1001

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  api:
    build: ./kanadex-api
    ports:
      - 5050:5050
    depends_on:
      - sftp
      - db


  client:
    build: ./kanadex-client
    ports:
      - 3000:3000
    depends_on:
      - api
