services:

  sftp:
    image: atmoz/sftp:alpine
    volumes:
        - ./upload:/home/foo/upload
    ports:
        - "2222:22"
    command: foo:pass:1001

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      
  
  api:
    build: ./kanadex-api
    ports:
      - "8080:8080"
    
    depends_on:
      - sftp
      - db


  client:
    build: ./kanadex-client
    ports:
      - "3000:3000"

    depends_on:
      - api
